# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    boxes = [
      { :name => "debian-buster-box", :box => "debian/buster64" },
      { :name => "ubuntu-focal-box", :box => "ubuntu/focal64" },
      { :name => "ubuntu-bionic-box", :box => "ubuntu/bionic64" }
    ]
    boxes.each do |opts|
      config.vm.define opts[:name] do |config|
        config.vm.box = opts[:box]
        if opts[:name] == "ubuntu-focal-box"
          config.vm.provider "virtualbox" do |vb|
            vb.customize [ "modifyvm", :id, "--uartmode1", "file", File::NULL ]
          end
        end
        if opts[:name] == boxes.last[:name]
          config.vm.provision "ansible" do |ansible|
            ansible.playbook = "test.yml"
            ansible.limit = "all"
          end
        end
      end
    end
  end